/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.SQLException;
import ControlData.Muc;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public final class QLMuc extends javax.swing.JFrame {
    public Muc MucDB = new Muc();
    public boolean cothem = true;
    public DefaultTableModel tableModel = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
          return false;
        }
    };
    /**
     * Creates new form QLMuc
     */
    public QLMuc() throws SQLException {
        initComponents();
        String [] colName = {"Mã Mực", "Tên Mực", "Giá Mực"};
        tableModel.setColumnIdentifiers(colName);
        tblQLMuc.setModel(tableModel);
        ShowData();
        SetKhoa(true);
        SetButton(false);
        
    }
    public void ShowData() throws SQLException{
        ResultSet rs = MucDB.ShowMuc();
        try {
            while (rs.next()){
                String row[] = new String[3];
                row[0]= rs.getString(1);
                row[1]= rs.getString(2);
                row[2]= rs.getString(3);
                tableModel.addRow(row);
            }
        } catch (SQLException e) {
        }
    }
    public void ClearData() throws  SQLException{
        //Lay chi so dong cuoi cung
        int n= tableModel.getRowCount()-1;
        for(int i=n;i>=0; i--)
            tableModel.removeRow(i);//Remove tung dong
    }
    public void SetKhoa(boolean a){
        txtTen.setEnabled(!a);
        txtGia.setEnabled(!a);
    }
    public void SetNull (){
        txtMa.setText(null);
        txtTen.setText(null);
        txtGia.setText(null);
    }
    public void SetButton (boolean a){
        btnLuu.setEnabled(a);
        btnKhongLuu.setEnabled(a);
        btnSua.setEnabled(!a);
        btnXoa.setEnabled(!a);
        btnThem.setEnabled(!a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        txtMa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQLMuc = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        txtGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnKhongLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Giá :");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel6.setText("VNĐ");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtMa.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ MỰC");

        tblQLMuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ));
        tblQLMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLMucMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblQLMuc);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Mã Mực :");

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        txtGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGiaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Tên Mực :");

        btnKhongLuu.setText("Không Lưu");
        btnKhongLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhongLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKhongLuu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnLuu)
                    .addComponent(btnKhongLuu)
                    .addComponent(btnThoat)
                    .addComponent(btnSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ClearData();
        } catch (SQLException ex) {
            Logger.getLogger(QLMuc.class.getName()).log(Level.SEVERE, null, ex);
        }
        SetKhoa(false);
        SetButton(true);   
        SetNull();
        cothem= true;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnKhongLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhongLuuActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null,"Kết quả sẽ bị hủy", "Thông báo",JOptionPane.CLOSED_OPTION );
        try {
            ClearData();
            ShowData();
        } catch (SQLException ex) {
            Logger.getLogger(QLGiay.class.getName()).log(Level.SEVERE, null, ex);
        }
        SetKhoa(true);
        SetButton(false);
        SetNull();
    }//GEN-LAST:event_btnKhongLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String Ten = txtTen.getText();
        if (txtMa.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Vui lòng chọn một sản cần xóa", "Thông báo", JOptionPane.CLOSED_OPTION);
        }else{
            if (JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa "+Ten+" không ?", "Thông báo",JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                     // yes option
                String Ma = txtMa.getText();
                try {
                    MucDB.DeleteData(Ma);
                    ClearData();
                    ShowData();
                    SetKhoa(true);
                    SetNull();
                } catch (SQLException ex) {
                    Logger.getLogger(QLMuc.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {           
            }
            
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblQLMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLMucMouseClicked
        // TODO add your handling code here:
         SetKhoa(true);
        int row = this.tblQLMuc.getSelectedRow();
        String Ma = this.tblQLMuc.getModel().getValueAt(row, 0).toString();
        try {
            ResultSet rs = MucDB.Show1Muc(Ma);
            if (rs.next()){
                txtMa.setText(rs.getString("MaMuc"));
                txtTen.setText(rs.getString("TenMuc"));
                txtGia.setText(rs.getString("GiaMuc"));
            }          
        } catch (SQLException ex) {
            Logger.getLogger(QLMuc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblQLMucMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
         if (txtMa.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Vui lòng chọn một sản cần sửa", "Thông báo", JOptionPane.CLOSED_OPTION);
        }else{
            SetKhoa(false);
            SetButton(true);
            cothem=false;
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String Ten = txtTen.getText();
        String Ma = txtMa.getText();
        String Gia = txtGia.getText();
        if (cothem == true){
            if(txtTen.getText().isEmpty()||txtGia.getText().isEmpty()){
                JOptionPane.showConfirmDialog(null, "Vui lòng điền đủ thông tin cần thêm", "Thông báo", JOptionPane.CLOSED_OPTION);
                SetNull();
                SetButton(true);
                try {
                    ClearData();
                } catch (SQLException ex) {
                    Logger.getLogger(QLMuc.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                //Kiểm tra nhập GIÁ có là SỐ hay không
                int sz = Gia.length();
                boolean KTso = true;
                for (int i = 0; i < sz; i++) {
                    if (!Character.isDigit(Gia.charAt(i)) ) {                  
                        KTso=false;
                    }
                }
                if(KTso==false){
                    JOptionPane.showConfirmDialog(null, "Vui lòng nhập giá đúng", "Thông báo", JOptionPane.CLOSED_OPTION);
                }
                else{
                    try {
                        int gias = Integer.parseInt(Gia);
                        MucDB.InsertData(Ten, gias);
                        ClearData();
                        ShowData();
                        SetNull();
                        SetKhoa(true);
                        SetButton(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(QLGiay.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        if (cothem==false){
            try {  
                int gias = Integer.parseInt(Gia);
                MucDB.EditData(Ma, Ten, gias);
                ClearData();
                ShowData();
                SetNull();
                SetKhoa(true);
                SetButton(false);
                cothem = true;
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        TrangChu frmtrTrangChu = new TrangChu();
        frmtrTrangChu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void txtGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_txtGiaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new QLMuc().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(QLMuc.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhongLuu;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblQLMuc;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
