package View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import  ControlData.AD;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class TrangChu extends javax.swing.JFrame {

    AD ad;
    public TrangChu() {
        initComponents();
        jLabel1.setText(ad.ten);
        checkUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src\\main\\java\\View\\image\\BACKGROUD3.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnBanHang = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuHeThong = new javax.swing.JMenu();
        btnDoiMK = new javax.swing.JMenu();
        btnQLtaiKhoan = new javax.swing.JMenu();
        btnDangXuat = new javax.swing.JMenu();
        menuCongCu = new javax.swing.JMenu();
        btnQLGiay = new javax.swing.JMenu();
        btnQLMuc = new javax.swing.JMenu();
        btnLoaiSP = new javax.swing.JMenu();
        btnSanpham = new javax.swing.JMenu();
        btnKhachHang = new javax.swing.JMenu();
        btnViTri = new javax.swing.JMenu();
        btnNhanVien = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBanHang.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btnThongKe.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Tên người truy cập:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1086, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        menuHeThong.setText("Hệ Thống");

        btnDoiMK.setText("Đổi mật khẩu");
        btnDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoiMKMouseClicked(evt);
            }
        });
        menuHeThong.add(btnDoiMK);

        btnQLtaiKhoan.setText("Quản lý tài khoản");
        btnQLtaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLtaiKhoanMouseClicked(evt);
            }
        });
        menuHeThong.add(btnQLtaiKhoan);

        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseClicked(evt);
            }
        });
        menuHeThong.add(btnDangXuat);

        jMenuBar2.add(menuHeThong);

        menuCongCu.setText("Công cụ quản lý");

        btnQLGiay.setText("Quản lý Giấy");
        btnQLGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLGiayMouseClicked(evt);
            }
        });
        menuCongCu.add(btnQLGiay);

        btnQLMuc.setText("Quản lý Mực");
        btnQLMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLMucMouseClicked(evt);
            }
        });
        menuCongCu.add(btnQLMuc);

        btnLoaiSP.setText("Quản lý Loại sản phẩm");
        btnLoaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoaiSPMouseClicked(evt);
            }
        });
        menuCongCu.add(btnLoaiSP);

        btnSanpham.setText("Quản lý Sản phẩm");
        btnSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanphamMouseClicked(evt);
            }
        });
        menuCongCu.add(btnSanpham);

        btnKhachHang.setText("Quản lý Khách hàng");
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseClicked(evt);
            }
        });
        menuCongCu.add(btnKhachHang);

        btnViTri.setText("Quản lý Vị trí");
        btnViTri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViTriMouseClicked(evt);
            }
        });
        menuCongCu.add(btnViTri);

        btnNhanVien.setText("Quản lý Nhân viên");
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseClicked(evt);
            }
        });
        menuCongCu.add(btnNhanVien);

        jMenuBar2.add(menuCongCu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseClicked
        try {
            KhachHang frmKH = new KhachHang();
            frmKH.btnChon.setVisible(false);
            frmKH.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnKhachHangMouseClicked

    private void btnDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMKMouseClicked
        DoiMK frmDoiMK = new DoiMK();
        frmDoiMK.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_btnDoiMKMouseClicked

    private void btnLoaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiSPMouseClicked
        try {
            LoaiSP frmLoaiSP = new LoaiSP();
            frmLoaiSP.setVisible(true); 
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnLoaiSPMouseClicked

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        BanHang frmCthd = new BanHang();
        frmCthd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanphamMouseClicked
        try {
            SanPham frmCthd = new SanPham();
            frmCthd.setVisible(true);
            this.setVisible(false);
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnSanphamMouseClicked

    private void btnQLMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLMucMouseClicked
        try {
            QLMuc frmCthd = new QLMuc();
            frmCthd.setVisible(true);
            this.setVisible(false);
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnQLMucMouseClicked

    private void btnQLGiayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLGiayMouseClicked
        try {
            QLGiay frmCthd = new QLGiay();
            frmCthd.setVisible(true);
            this.setVisible(false);
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnQLGiayMouseClicked

    private void btnViTriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViTriMouseClicked
        try {
            ViTri frmNhanVien = new ViTri();
            frmNhanVien.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViTriMouseClicked

    private void btnNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseClicked
        try {
            NhanVien frmNhanVien = new NhanVien();
            frmNhanVien.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_btnNhanVienMouseClicked

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        try {
            BangThongKeDoanhThu frmBangThongKeDoanhThu;
            frmBangThongKeDoanhThu = new BangThongKeDoanhThu();
            frmBangThongKeDoanhThu.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }    
        this.dispose();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnQLtaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLtaiKhoanMouseClicked
        try {
            QLTaiKhoan frmNhanVien = new QLTaiKhoan();
            frmNhanVien.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_btnQLtaiKhoanMouseClicked

    private void btnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseClicked
        if ((JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất", "Thông báo", 2))==0){
            DangNhap frmChu = new DangNhap();
            frmChu.setVisible(true);
            this.dispose();
        }
        else{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_btnDangXuatMouseClicked

//check tài khoản đăng nhập để phân quyền    
    public void checkUser (){
        if (!"admin".equals(ad.user)){
            btnThongKe.hide();
            btnQLtaiKhoan.hide();
            btnViTri.hide();
            btnNhanVien.hide();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TrangChu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JMenu btnDangXuat;
    private javax.swing.JMenu btnDoiMK;
    private javax.swing.JMenu btnKhachHang;
    private javax.swing.JMenu btnLoaiSP;
    public javax.swing.JMenu btnNhanVien;
    private javax.swing.JMenu btnQLGiay;
    private javax.swing.JMenu btnQLMuc;
    private javax.swing.JMenu btnQLtaiKhoan;
    private javax.swing.JMenu btnSanpham;
    private javax.swing.JButton btnThongKe;
    public javax.swing.JMenu btnViTri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCongCu;
    private javax.swing.JMenu menuHeThong;
    // End of variables declaration//GEN-END:variables

    void isVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
